png("plot4.png")
par(mfcol = c(2,2))
plot(data$Time, data$Global_active_power, ylab = "Global Active Power (killowatts)", xlab = "", type = "l")
plot(data$Time, data$Sub_metering_1, ylab = "Energy sub metering", xlab = "", type = "l")
lines(data$Time, data$Sub_metering_2, col = "red")
lines(data$Time, data$Sub_metering_3, col = "blue")
legend("topright", names(data)[7:9], lty = 1, col = c("black", "red", "blue"), bty = "n")
plot(data$Time, data$Voltage,ylab = "Voltage", xlab = "datetime", type = "l")
plot(data$Time, data$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type = "l")
dev.off()